apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tekton-custom-task
    app.kubernetes.io/managed-by: kustomize
  name: tekton-custom-task-admin-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - approvaltasks
  verbs:
  - '*'
- apiGroups:
  - edp.epam.com
  resources:
  - approvaltasks/status
  verbs:
  - get
